# Generated by Django 4.0 on 2021-12-15 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldA1', models.CharField(max_length=100, unique=True)),
                ('fieldA2', models.TextField(blank=True, null=True)),
                ('fieldA3', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('field4', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldB1', models.CharField(blank=True, max_length=70, null=True)),
                ('fieldB2', models.PositiveIntegerField(default=0)),
                ('fieldB3', models.BooleanField(default=False)),
                ('field4', models.BooleanField(default=True)),
                ('model_a_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_b_field', to='polls.modela')),
            ],
        ),
        migrations.DeleteModel(
            name='address',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
