# Generated by Django 4.0 on 2021-12-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_address_customer_remove_modelb_model_a_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='idkey',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
