# Generated by Django 4.0 on 2021-12-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_gender_remove_address_idkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='model_a_field',
        ),
        migrations.DeleteModel(
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='address',
        ),
    ]
