# Generated by Django 4.0 on 2021-12-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_address_model_a_field_delete_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
