# Generated by Django 4.0 on 2021-12-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_remove_address_customer_field_address_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
