# Generated by Django 4.0 on 2021-12-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_college_department_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customer',
            new_name='GetTouch',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
